export const ARTICLES_LIST_REQUEST = 'ARTICLES_LIST_REQUEST';
export const ARTICLES_LIST_SUCCESS = 'ARTICLES_LIST_SUCCESS';
export const ARTICLES_LIST_FAIL = 'ARTICLES_LIST_FAIL';
export const ARTICLES_DETAILS_REQUEST = 'ARTICLES_DETAILS_REQUEST';
export const ARTICLES_DETAILS_SUCCESS = 'ARTICLES_DETAILS_SUCCESS';
export const ARTICLES_DETAILS_FAIL = 'ARTICLES_DETAILS_FAIL';